### ISSUE TITLE
What is the reason for home:ro?

### ISSUE THREAD

**Issue by Cliveptr** [flathub/fi.skyjake.Lagrange#1]
I'm not too sure what share=ipc does, but is that necessary for anything? I disabled it and Lagrange seems to be functioning as before. [Flatpak docs](https://github.com/flatpak/flatpak-docs/blob/master/docs/sandbox-permissions.rst#standard-permissions) say it's necessary for X11 (which I'm using).

P.S. thanks for the Flatpak :)

**Comment by skyjake** [comment]
> What is the reason for home:ro?

The user is able to drag and drop a file from anywhere in their home folder on the Lagrange window to open it. This feature is present because Lagrange doesn't have an Open File dialog.

The use case is to enable easy previewing of locally written .gmi files, for example.

> what share=ipc does, but is that necessary for anything? 

I'm not clear on the technical details here when it comes to Flatpak sandboxing, but interprocess communication (IPC) is presumably needed for certain X11 features.
